# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  base_rotation_joint:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: true
    max_acceleration: 1
  elbow1_joint:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: true
    max_acceleration: 1
  elbow2_joint:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: true
    max_acceleration: 1
  left_finger_joint:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: true
    max_acceleration: 1
  right_finger_joint:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: true
    max_acceleration: 1
  shoulder_joint:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: true
    max_acceleration: 1
  wrist_joint:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: true
    max_acceleration: 1
