komodo: true

left_finger_topic_pub: 'left_finger_controller/command'
left_finger_topic_sub: 'left_finger_controller/state'
left_finger_joint: 'left_finger_joint'

right_finger_topic_pub: 'right_finger_controller/command'
right_finger_topic_sub: 'right_finger_controller/state'
right_finger_joint: 'right_finger_joint'

                              
# RiCBoard                                
battery_pin: 17
battery_voltage_divider_ratio: 11.0
battery_max: 29.3
battery_min: 24.0

imu_fusion_hz: 50
imu_enable_gyro: true
imu_enable_fuse_compass: true
imu_frame_id: 'base_link'
imu_linear_acc_fix: [0, 1, 0,
                     -1, 0, 0,
                     0, 0, -1]

imu_angular_velocity_fix: [0, -1, 0,
                           1, 0, 0,
                           0, 0, 1]

imu_magnetometer_fix: [1, 0, 0,
                       0, 1, 0,
                       0, 0, 1]

imu_rotation_fix: [0, 1, 0,
                   1, 0, 0,
                   0, 0, -1]

imu_rotation_offset: [0, -3.141592, 0]

ultrasonic_size: 3

ultrasonic0_pin: 14
ultrasonic0_frame_id: 'left_urf_link'
ultrasonic0_topic_name: 'URF/left'
ultrasonic0_sonar_name:  'Max_Sonar_HRLV'

ultrasonic1_pin: 15
ultrasonic1_frame_id: 'right_urf_link'
ultrasonic1_topic_name: 'URF/right'
ultrasonic1_sonar_name:  'Max_Sonar_HRLV'

ultrasonic2_pin: 16
ultrasonic2_frame_id: 'rear_urf_link'
ultrasonic2_topic_name: 'URF/rear'
ultrasonic2_sonar_name:  'Max_Sonar_HRLV'

close_motor_size: 2

motor0_motor_type: 0
motor0_encoder_pin_A: 27
motor0_encoder_pin_B: 28
motor0_lpf_hz_speed: 80
motor0_lpf_hz_input: 1000
motor0_lpf_alpha_speed: 0.27
motor0_lpf_alpha_input: 1.0
motor0_pid_hz: 1000
motor0_ppr: 2503
motor0_timeout: 0
motor0_motor_direction: 1
motor0_encoder_direction: -1
motor0_kp: 37.0
motor0_ki: 14.0
motor0_kd: 0.0
motor0_kff: 14.0
motor0_max_set_point_speed: 21.872
motor0_min_set_point_speed: -21.872
motor0_max_set_point_position: 0.0
motor0_min_set_point_position: 0.0
motor0_limit: 0.2
motor0_stop_limit_max: 25.0
motor0_stop_limit_min: -25.0
motor0_motor_address: 0
motor0_motor_emergency_pin: 12
motor0_motor_emergency_pin_type: 1
motor0_joint: ['FL_wheel_joint', 'RL_wheel_joint']
motor0_mode: 0
motor0_bais_min: -1
motor0_bais_max: 1


motor1_motor_type: 0
motor1_encoder_pin_A: 29
motor1_encoder_pin_B: 30
motor1_encoder_direction: 1
motor1_lpf_hz_speed: 80
motor1_lpf_hz_input: 1000
motor1_lpf_alpha_speed: 0.27
motor1_lpf_alpha_input: 1.0
motor1_pid_hz: 1000
motor1_ppr: 2503
motor1_timeout: 0
motor1_motor_direction: -1
motor1_kp: 37.0
motor1_ki: 14.0
motor1_kd: 0.0
motor1_kff: 14.0
motor1_max_set_point_speed: 21.872
motor1_min_set_point_speed: -21.872
motor1_max_set_point_position: 0.0
motor1_min_set_point_position: 0.0
motor1_limit: 0.2
motor1_stop_limit_max: 25.0
motor1_stop_limit_min: -25.0
motor1_motor_address: 1
motor1_motor_emergency_pin: 12
motor1_motor_emergency_pin_type: 1
motor1_joint: ['FR_wheel_joint', 'RR_wheel_joint']
motor1_mode: 0
motor1_bais_min: -1
motor1_bais_max: 1



gps_baudrate: 9600
gps_topic_name: 'gps'
gps_frame_id: 'base_link'

#RiCBoard



left_finger_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: left_finger_joint
    joint_speed: 0.2
    max_torque: 0.1
    motor:
        id: 1
        init: 2048
        min: 1480
        max: 2622

right_finger_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_finger_joint
    joint_speed: 0.2
    max_torque: 0.1
    motor:
        id: 2
        init: 2048
        min: 1480
        max: 2622
